#!/bin/bash

echo "Setting up Vercel environment variables..."
echo ""
echo "You'll need to provide the following values:"
echo "1. NEXT_PUBLIC_SUPABASE_URL - Your Supabase project URL"
echo "2. NEXT_PUBLIC_SUPABASE_ANON_KEY - Your Supabase anon key"
echo "3. NEXT_PUBLIC_APP_URL - Your Vercel app URL (will be provided after deployment)"
echo ""
echo "To get your Supabase values:"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to Settings > API"
echo "4. Copy the Project URL and anon public key"
echo ""
echo "Run these commands to add the environment variables:"
echo ""
echo "npx vercel env add NEXT_PUBLIC_SUPABASE_URL"
echo "npx vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "npx vercel env add NEXT_PUBLIC_APP_URL"
echo ""
echo "After adding the environment variables, redeploy with:"
echo "npx vercel --prod --yes"
